name: "Build and push package"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Log in to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build and publish changed packages
        run: |
          npm run find-changed-packages
          changed_packages=$(<changed-packages.json)
          package_names=($(echo $changed_packages | jq -r '.[].name'))
          echo "Changed packages: $package_names"

          for package in $package_names"; do
            package=$(echo $package | tr -d '[:space:]')
            echo "Changed package: $package"
            if [ -n "$package" ]; then
              cd packages/$package
              npm run build-package
              npm run publish-package
              git add .
              git commit -m "Bump version for $package"
              git push origin main
              cd ../../
            fi
          done
