name: "Build and publish package"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Log in to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Find changed packages
        run: npm run find-changed-packages

      - name: Build changed packages
        run: |
          changedPackages=$(cat changed-packages.json)

          echo "Chnaged-packages:$changedPackages"

          cd src

          for package in $(echo "$changedPackages" | jq -c '.[]'); do
              packageName=$(echo "$package" | jq -r .name)
              packageName=${packageName#snmt-}
              echo "packageName:$packageName"
              cd packages/$packageName
              npm install --legacy-peer-deps
              npm run build-package
              cd ../../
          done

      - name: Publish changed packages
        run: |
          git add .
          git commit -m "feat: Update packages"
          npx lerna publish 'patch' --yes
          git push origin main
